### ISSUE TITLE
User can search art

### ISSUE THREAD

**Issue by GCarolyne** [GCarolyne/Virtual-Art-Gallery#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

They will be able to use the search bar to find the Artist or Art work they desire. 
Also, click on the "My Collection" button and see the empty collection. 
Use app on mobile and desktop responsiveness. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

One the Welcome page the user will be able to see a static image of a personal reflecting on a painting. Above this the user will read a short description about what the website is intended for. Using a Artist name or Painting name the user will be able to search and filter through the Art Institute of Chicago domain. On the top right hand corner the user will be able to click a button described as "My Collection" to view a empty Collection page. 
The page will be prepared with the CSS responsiveness for both mobile and desktop. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-11-26 at 11 04 46 AM](https://github.com/user-attachments/assets/895773d3-9b84-469c-ab36-2e3c35f5bb4e)
![Screenshot 2024-11-26 at 11 05 00 AM](https://github.com/user-attachments/assets/56ae6505-46d7-4907-9bb3-92cea55ca4b3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a responsive mobile/desktop CSS layout for Welcome page. 
- [x] Create Homepage
- [x] When the user searches something, call your api. 
- [x] Show the results. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
